## Programming Basic Assignment 7

### 1. Write a Python Program to find sum of array?

In [48]:
def summation(x):          # method - 1
    import numpy as np
    x = np.array(x)
    return x.sum()

In [49]:
summation([[1,2,3],[7,8,9]])

30

In [205]:
def summation2(x):         # method - 2
    import numpy as np
    x = np.array(x)
    total = 0
    if x.ndim >=2:
        for i in range(x.shape[0]):
            for j in range(x.shape[1]):
                total = total + x[i][j]
        return total
    else:
        for i in range(len(x)):
            total = total + x[i]
        return total

In [206]:
summation2([[1,2,3],[7,8,9]])

30

In [207]:
summation2([1,2,3])

6

### 2. Write a Python Program to find largest element in an array?


In [122]:
def maximum(x):      # method - 1
    import numpy as np
    x = np.array(x)
    return x.max()

In [123]:
 maximum([[1,2,3],[7,8,9]])

9

In [208]:
def maximum2(x):      # method - 2
    import numpy as np
    x = np.array(x)

    if x.ndim >= 2:
        a = x[0][0]
        for i in range(0,x.shape[0]):
            for j in range(0,x.shape[1]):
                if x[i][j] > a:
                    a = x[i][j]
                else:
                    a = a
        return a
    else:
        a = x[0]
        for i in range(0,len(x)):
            if x[i] > a:
                a = x[i]
            else:
                a = a
        return a


In [209]:
maximum3([[1,2,10],[4,5,1]])

10

In [210]:
maximum3([[1,2,10],[4,50,1]])

50

In [211]:
maximum3([1,2,10,4,5,1,2])

10

### 3. Write a Python Program for array rotation?

In [73]:
def rotation(array,shift,axis):
    import numpy as np
    x = np.array(array)
    if x.ndim == 1:
        axis = 0
        return np.roll(x,shift,axis)
    else:
        return np.roll(x,shift,axis)

In [78]:
rotation([[1,2,3],[4,5,6]],1,1)

array([[3, 1, 2],
       [6, 4, 5]])

In [80]:
rotation([1,2,3],2,1)

array([2, 3, 1])

In [81]:
rotation([1,2,3],1,0)

array([3, 1, 2])

### 4. Write a Python Program to Split the array and add the first part to the end?

In [120]:
def split_addition(array,position):
    import numpy as np
    x = np.array(array)
    return np.concatenate((x[position:],x[:position]), axis = 0)

In [212]:
split_addition([1,2,3,4],2)

array([3, 4, 1, 2])

### 5. Write a Python Program to check if given array is Monotonic?

In [258]:
def check(array):
    import numpy as np
    x = np.sort(np.array(array),0)
    y = x[-1::-1]
    if np.array_equal(array,x): 
        print('monotonic')
   # elif (y == check).all():
    #    print('monotonic')
   # else:
    #    print('non-monotonic')

In [259]:
check([1,2,3,4])

In [260]:
check([4,3,2,1])

In [261]:
check([4,5,2,1])

In [249]:
x = np.sort(np.array([1,2,4,3]),0)
x[-1::-1]

array([4, 3, 2, 1])

In [216]:
x = np.sort(np.array([[2,5,1,4],[5,6,2,8]]),1)
x

array([[1, 2, 4, 5],
       [2, 5, 6, 8]])