# Python Basic Programming Assignment 8

### 1. Write a Python Program to Add Two Matrices?

In [2]:
def add(x1,x2):            # method - 1
    import numpy as np
    x1 = np.array(x1)
    x2 = np.array(x2)
    return x1 + x2

In [4]:
add([[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]])

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
def add(x1,x2):            # method - 2
    import numpy as np
    x1 = np.array(x1)
    x2 = np.array(x2)
    shape1 = np.shape(x1)
    shape2 = np.shape(x2)
    x3 = np.zeros(shape = shape1)
    if x1.ndim >= 2:
        for i in range(shape1[0]):
            for j in range(shape1[1]):
                x3[i,j] = x1[i,j] + x2[i,j]
        return x3
    else:
        for i in range(len(x1)):
                x3[i] = x1[i] + x2[i]
        return x3

In [18]:
add([1,2,3],[1,2,3])

array([2., 4., 6.])

In [20]:
add([[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]])

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

### 2. Write a Python Program to Multiply Two Matrices?

In [21]:
def multiplication(x1,x2):            # method - 1
    import numpy as np
    x1 = np.array(x1)
    x2 = np.array(x2)
    return x1 * x2

In [22]:
multiplication([[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]])

array([[ 1,  4,  9],
       [16, 25, 36]])

In [23]:
def multiplication(x1,x2):            # method - 2
    import numpy as np
    x1 = np.array(x1)
    x2 = np.array(x2)
    shape1 = np.shape(x1)
    shape2 = np.shape(x2)
    x3 = np.zeros(shape = shape1)
    if x1.ndim >= 2:
        for i in range(shape1[0]):
            for j in range(shape1[1]):
                x3[i,j] = x1[i,j] * x2[i,j]
        return x3
    else:
        for i in range(len(x1)):
                x3[i] = x1[i] * x2[i]
        return x3

In [24]:
multiplication([1,2,3],[1,2,3])

array([1., 4., 9.])

In [25]:
multiplication([[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]])

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

### 3. Write a Python Program to Transpose a Matrix?

In [26]:
def transpose(x):            # method - 1
    import numpy as np
    x = np.array(x)
    return np.transpose(x)

In [29]:
transpose([1,2,3])

array([1, 2, 3])

In [28]:
transpose([[1,2,3],[4,5,6]])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [60]:
def transpose(x):            # method - 2
    import numpy as np
    x = np.array(x)
    shape = np.shape(x)
    
    if x.ndim >= 2:
        x3 = np.zeros(shape = (shape[1],shape[0]))
        for i in range(shape[0]):
            for j in range(shape[1]):
                x3[j,i] = x[i,j]
        return x3
    else:
        x3 = np.zeros(shape = (len(x),1))
        for i in range(len(x)):
                x3[i,0] = x[i]
        return x3

In [61]:
transpose([1,2,3])

array([[1.],
       [2.],
       [3.]])

In [62]:
transpose([[1,2,3],[4,5,6]])

array([[1., 4.],
       [2., 5.],
       [3., 6.]])


### 4. Write a Python Program to Sort Words in Alphabetic Order?


In [91]:
import numpy as np  # method - 1
def sort(x):
    x = np.array(x)
    return np.sort(x)


In [93]:
y = sort(['apple','cat','Ball','Apple'])
y

array(['Apple', 'Ball', 'apple', 'cat'], dtype='<U5')

### 5. Write a Python Program to Remove Punctuation From a String?

In [165]:
def remove_punctuation(x):
    y = ''
    for i in range(len(x)):
        if x[i].isalpha():
            #print(x[i])
            y = y + x[i]
    return y
    
            

In [166]:
remove_punctuation('he_llo')

'hello'

In [167]:
remove_punctuation('world!!')

'world'